Fix issue causing bracken-build to error out if database.kraken exists

diff --git a/bracken-build b/bracken-build
--- a/bracken-build
+++ b/bracken-build
@@ -185,16 +185,16 @@ else
         #database.kraken not found, must create
         echo "      >> ${KINSTALL}kraken --db $DATABASE --threads ${THREADS} $filenames > $DATABASE/database.kraken.tmp"
         ${KINSTALL}kraken --db $DATABASE --threads ${THREADS} $filenames > $DATABASE/database.kraken.tmp
-    fi
 
-if [ $0 -eq 0 ]
-then
-    mv $DATABASE/database.kraken.tmp $DATABASE/database.kraken
-    echo "          Finished creating database.kraken [in DB folder]"
-else
-    rm $DATABASE/database.kraken.tmp
-    echo "          Unable to create database.kraken [in DB folder]"
-    exit 1
+    if [ $0 -eq 0 ]
+    then
+        mv $DATABASE/database.kraken.tmp $DATABASE/database.kraken
+        echo "          Finished creating database.kraken [in DB folder]"
+    else
+        rm $DATABASE/database.kraken.tmp
+        echo "          Unable to create database.kraken [in DB folder]"
+        exit 1
+    fi
 fi
 #Generate databaseXmers.kmer_distrib
 #DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
