Speed up kmer_distr especially for longer reads (#275)
* Reduce memory overhead and exit early if not able to create database.kraken

* Fix issue causing bracken-build to error out if database.kraken exists

* Do not override the compiler preference of user, default to g++ only on Linux

* Speed up kmer_distr especially for longer read lengths

---------

Co-authored-by: Jen Lu <jennifer.lu717@gmail.com>

diff --git a/bracken-build b/bracken-build
--- a/bracken-build
+++ b/bracken-build
@@ -169,6 +169,7 @@ then
     #database.kraken.tsv exists, skip
     echo "          database.kraken.tsv exists, skipping creation...."
     ln -s $DATABASE/database.kraken.tsv $DATABASE/database.kraken
+
 else
     filenames=`find -L $DATABASE/library \( -name "*.fna" -o -name "*.fa" -o -name "*.fasta" \) -print`
     if [ $KRAKEN == "kraken2" ]
@@ -185,16 +186,17 @@ else
         #database.kraken not found, must create
         echo "      >> ${KINSTALL}kraken --db $DATABASE --threads ${THREADS} $filenames > $DATABASE/database.kraken.tmp"
         ${KINSTALL}kraken --db $DATABASE --threads ${THREADS} $filenames > $DATABASE/database.kraken.tmp
+
+    if [ $0 -eq 0 ]
+    then
+        mv $DATABASE/database.kraken.tmp $DATABASE/database.kraken
+        echo "          Finished creating database.kraken [in DB folder]"
+    else
+        rm $DATABASE/database.kraken.tmp
+        echo "          Unable to create database.kraken [in DB folder]"
+        exit 1
     fi
-fi
-if [ $? -eq 0 ]
-then
-    mv $DATABASE/database.kraken.tmp $DATABASE/database.kraken
-    echo "          Finished creating database.kraken [in DB folder]"
-else
-    rm $DATABASE/database.kraken.tmp
-    echo "          Unable to create database.kraken [in DB folder]"
-    exit 1
+
 fi
 #Generate databaseXmers.kmer_distrib
 #DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
